import argparse

def parse_args():
    parser = argparse.ArgumentParser(description="Arguments for training DSRGAT model")
    parser.add_argument('--batch_size', type=int, default=200)
    parser.add_argument('--aggregator_type', type=str, default='gat', choices=['mean', 'seq', 'maxpool', 'meanpool', 'gcn', 'attn', 'gat'])
    parser.add_argument('--act', type=str, default='relu', choices=['linear', 'relu', 'elu'])
    parser.add_argument('--max_degree', type=int, default=50)
    parser.add_argument('--learning_rate', type=float, default=0.001)
    parser.add_argument('--hidden_size', type=int, default=100)
    parser.add_argument('--embedding_size', type=int, default=50)
    parser.add_argument('--emb_user', type=int, default=50)
    parser.add_argument('--max_length', type=int, default=20)
    parser.add_argument('--samples_1', type=int, default=10)
    parser.add_argument('--samples_2', type=int, default=5)
    parser.add_argument('--dim1', type=int, default=100)
    parser.add_argument('--dim2', type=int, default=100)
    parser.add_argument('--model_size', type=str, default='small', choices=['small', 'big'])
    parser.add_argument('--dropout', type=float, default=0.0)
    parser.add_argument('--weight_decay', type=float, default=0.0)
    parser.add_argument('--print_every', type=int, default=100)
    parser.add_argument('--val_every', type=int, default=500)
    parser.add_argument('--ckpt_dir', type=str, default='save/')
    parser.add_argument('--epochs', type=int, default=20)
    parser.add_argument('--decay_steps', type=int, default=400)
    parser.add_argument('--decay_rate', type=float, default=0.98)
    parser.add_argument('--local_only', action='store_true')
    parser.add_argument('--global_only', action='store_true')
    return parser.parse_args()